### ISSUE TITLE
JOSS review: Fix license

### ISSUE THREAD

**Issue by salbalkus** [nppackages/lpcde#6]
Raising as part of JOSS review openjournals/joss-reviews#7241

Though the MIT license is contained in R/lpcde/LICENSE.md, it looks like the LICENSE plain text file does not contain a valid license, which is required by JOSS. In addition to updating the plain text file, I would recommend moving or copying the license to the top level of the repo as well, so that it is clear the license applies to all code contained within it and is easy to find. I think this is why it was not detected automatically by the editorial bot.

**Comment by rajitachandak** [comment]
We have fixed the license issue with the latest version of the package (0.1.5) on CRAN.

**Comment by salbalkus** [comment]
Excellent! Note that it looks like you've included an MIT license, but the license shield in the first line of the README says GPLv2 and the "license" tab says GPL-3.0; you'll probably want to make these consistent with the MIT license.

**Comment by rajitachandak** [comment]
Thanks for pointing that out! I've made the license GPL >=3.0 consistent across all files. This should be reflecting on CRAN soon.
