### ISSUE TITLE
JOSS review: Software paper citations and spelling

### ISSUE THREAD

**Issue by salbalkus** [nppackages/lpcde#7]
Raising as part of JOSS review openjournals/joss-reviews#7241

I found a few small issues in the paper:
1. Citations are missing DOI numbers
2. Title of "Cattaneo, M. D., Chandak, R., Jansson, M., & Ma, X. (2024a). Local polynomial conditional density estimators. Bernoulli, 30(4), 3193–3223" I believe should be corrected to say "**Boundary adaptive** local polynomial conditional density estimators"
3. Spelling mistake: "conditioal PDF" at the top of page 2

**Comment by salbalkus** [comment]
Oh, and one more comment: I would also recommend citing the R package / JOSS paper [haldensify: Highly adaptive lasso conditional density estimation in R](https://joss.theoj.org/papers/10.21105/joss.04522) by Hejazi, van der Laan, and Benkeser (2022) and possibly adding it to your table of comparisons.

**Comment by rajitachandak** [comment]
Thank you for bringing these points to our attention.
  (a) We have added DOIs to references where available.
  (b) We have fixed the reference.
  (c) We have fixed the spelling mistake.
  (d) We have added haldensify to the table and compared its capabilities along with the other packages.
